# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7803642dd749b95e9c036e0f123e75bfd8eaf07e3013b54fd64286e727a53f16d854d8923e94398ee6a23fcc7a13e9a6bf1db1a6af15fcc81e4eb3431cf48e81

test:
  secret_key_base: 4774bfde09fcaf29d402f0a304a5e54b01e100cf91427f5574a8fe52a92947bcf6d30590abd927d596989bd870b9ad69e69b00daa119477abbc3a24af7d9e5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
